### ISSUE TITLE
R interface

### ISSUE THREAD

**Issue by maxbiostat** [bioDS/RNNI_code#4]
Hi, awesome work here!

I'd like to write an R interface for the routines in your repo. 

Initially, all I need is to compute `rNNI(t1, t2)` for two trees, but it would also be nice to write something for the graph, diameter, etc.

I'm thinking of something along the lines of the wrappers for [rspr](https://github.com/cwhidden/rspr/tree/master/R).

I just need a couple pointers. Should I write something that calls C code directly, or should I use a Python-R interface to use the  higher level functions in the repo (like done [here](https://github.com/mattpitkin/lintegrate)) ? Which routines should I focus on?

I'm happy to do quick a call to discuss these things.

Thanks in advance!

**Comment by lenacoll** [comment]
Hi!

That sounds awesome.

We have two different implementations to compute the rnni distance. The most efficient way to do this is to use the algorithm FindPath.

In this repo everything is written in Python. The C code here is only used to compute distances between all trees in the graph with Seidel's algorithm, which was used for testing purposes and is not so relevant anymore, because we can compute distances more efficiently with FindPath.
The implementation of FindPath can be found in findpath.py.

I do however recommend considering to use our more efficient implementation, which you can find in our repo "treeOclock". The implementation of FindPath there is more efficient than the one in this repo (RNNI_code).
There we also have written a python interface to read trees in newick format or in nexus files. So it might be useful for you to use these functions. They are in the submodule dct_parser in the git repo treeOclock. The function to compute the RNNI distance there is "findpath_distance" in tree.c.

I hope this could help. I'm also happy to discuss further in a call, just flick me an email.

Cheers
